### ISSUE TITLE
GENESIS OF OPEN SOURCE IN IKOT-EKPENE | IKOT-EKPENE - 2021/06/25

### ISSUE THREAD

**Issue by favourmark05** [oscafrica/chapter-leads-hub#13]
## Event information
_Please complete all applicable._

- **Event name**: GENESIS OF OPEN SOURCE IN IKOT-EKPENE
- **Event date**: 2021/06/25
- **Estimated number of attendees**: 25 - 50
- **Event location**: IKOT-EKPENE, AKWA-IBOM STATE, NIGERIA (REMOTE)
- **Event description**: A meetup event to enlighten tech enthusiasts in Ikot Ekpene local government area on vast opportunities available via OSCA ( what it is, how to contribute to open source, and its accompanying benefits).OSCA Ikot Ekpene chapter is keen to kick off her inaugural meetup event aimed at promoting awareness and inclusiveness. Thus, serving as a link to collaborations in the world community. The meetup event is proposed to be a one-day event. The highlight will include:
What Open Source is
How one can contribute to open source
Importance of Open Source

## How does this benefit your chapter?
_Please let us know why we should approve this event._
This is the first time Open Source is having a chapter here in Ikot-Ekpene, and most people do not have a solid background of what Osca is and all about it and the importance of Open Source. This event will center on introducing Open Source Community to them, why they should contribute to open source, the benefit and importance of contributing to Open Source (both individual benefit and global benefit) 

## What help do you need with this event?
_Tell us how Open Source Community Africa can help with this event._
NOTHING

## Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [ ] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**:
- [ ] Your event is approved.
- [ ] Your event's RSVP page has been created on [Open Collective](https://opencollective/osca).
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

@BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, thanks for submitting this ticket!

Your request doesn't seem to follow the issue template provided. Kindly check again, make changes where necessary, and let us know. Please follow the guidelines strictly, using all required headings to help us review and get back to you. Do let us know if you need any help; cheers!

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji corrections has been made, thanks for the observation, please if there is any other i should correct please do pint it out for me
thanks
kind Regards
Mfonido Mark
Osca Lead Ikot-Ekpene

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, thanks for your swift response.

The changes look good. Kindly include the checklist section and check as required in the template. Also, the event budget you submitted via the request form should be a budget only and not a proposal. Do let us know if you need any help; cheers!

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji,
Corrections have been made, and the checklist has been added, the budget summary also has been corrected.
thanks for your observations.
Expecting your reply soonest.

kind regards,
Mfonido Mark
Osca Lead Ikot-Ekpene

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, thanks for making the changes and for your patience.

After reviewing your event request, we have a few feedbacks:

1. We don't advise you to host a physical event yet due to the still ongoing COVID-19 pandemic unless your local government advises you to, with which you should follow the restrictions and guidelines provided.

2. Looking that this is your first event and reviewing your budget, estimated number of attendees, and the scope of this event (as an introduction to open source and your chapter), we will advise you to organize a virtual event for your first event to better allow you define your local community, identify members, and bring them together before you organize a physical event.

Do let us know what you think and what you need to make the virtual event a success; cheers!

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji , 
With respect to your recent response 

The first concern
The ban on religious, social and any other form of gathering has since been lifted in the state. Thus, Ikot Ekpene local government gives full approval to host events by individuals or groups in compliance with COVID19 guidelines. 

The second concern
Judging from past personal experiences while attending physical or virtual events.  The latter amass a fewer number of participants compared to the former. However, as our demographic of interest are alien to the fundamental concepts of Open Source contributions, it will be pertinent to host a physical inaugural event as the subsequent meetups could take the virtual route. 

I anticipate..... 
Thanks and Kind Regards,
Mfonido Mark

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, sincere apologies for the delayed response. This is due to the multiple internal meetings we had concerning physical events and how we want to support you and your community. Here are the feedbacks we have for you:

We totally agree with your idea. Yes, physical events indeed amass more attendees than virtual events, which is appropriate for an inaugural event for a community that is alien to your community's goals. However, we still don't advise you to host a physical event yet due to the ongoing COVID-19 pandemic, and it is ideal for you to host a virtual event and keep yourself and your community safe. Also, the Federal Government of Nigeria recently announced a restriction on public gatherings from 11th May till 11th June 2021, which further confirms the need to go remote for now till the virus is contained.

Despite all said, our plans to kick-start the chapter's program was built around virtual and remote activities due to all that's happening globally, so we are not fully ready financially and resource-wise to shoulder the costs of hosting a physical event. Howeever, we are actively working to prepare ourselves for the post-remote life when you are fully allowed to gather your community physically. Be rest assured that we will support you to host physical events when the time is right.

So, we advise that you pick another date for your event (we apologize for keeping you waiting for this long; this is our fault and not yours) and make a new plan/budget to host a virtual event. Please let us know how we can support you in making your inaugural virtual event a success. Support here can include requesting an internet subscription for yourself or your community members as required. We also encourage you to build your community and outreach to neighboring communities to expose them to the amazing stuff you have planne. This will help make your first event even more successful and impactful. 

Lastly, there are a couple of things that need to be improved in your budget, especially around allocation and descriptive communication. Hence, we will discuss more about this generally in the next leads community call so you and other leads can learn about what we expect from you in terms of budgeting. Apologies once again for any inconvenience this will cause you. We're super proud of you and your community and can't wait to see you shine.

Do let us know if you need anything, and we'll be here to help. Cheers!

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05 👋🏾

We haven't heard from you for a while now.

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji 
Apologies i have been off for some time now, i was trying to sort out some things with my core team members, and we have come to some agreement.
i will be sending in a proposal immediately after this.

Thanks,
Mfonido Mark

**Comment by favourmark05** [comment]
## Event information
_Please complete all applicable._

- **Event name**: GENESIS OF OPEN SOURCE IN IKOT-EKPENE
- **Event date**: 2021/06/25
- **Estimated number of attendees**: 25 - 50
- **Event location**: IKOT-EKPENE, AKWA-IBOM STATE, NIGERIA (REMOTE)
- **Event description**: A meetup event to enlighten tech enthusiasts in Ikot Ekpene local government area on vast opportunities available via OSCA ( what it is, how to contribute to open source, and its accompanying benefits).OSCA Ikot Ekpene chapter is keen to kick off her inaugural meetup event aimed at promoting awareness and inclusiveness. Thus, serving as a link to collaborations in the world community. The meetup event is proposed to be a one-day event. The highlight will include:
What Open Source is
How one can contribute to open source
Importance of Open Source


## How does this benefit your chapter?
_Please let us know why we should approve this event._
This is the first time Open Source is having a chapter here in Ikot-Ekpene, and most people do not have a solid background of what Osca is and all about it and the importance of Open Source. This event will center on introducing Open Source Community to them, why they should contribute to open source, the benefit and importance of contributing to Open Source (both individual benefit and global benefit) 

## What help do you need with this event?
_Tell us how Open Source Community Africa can help with this event._
NOTHING

## Checklist

**Before you post the issue**:
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**:
- [ ] Your event is approved.
- [ ] Your event's RSVP page has been created on [Open Collective](https://opencollective/osca).
- [ ] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.


@BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
Hi, @favourmark05, thanks for the update.

Kindly make the changes in your initial submission. We'll review your proposal afterward; cheers!

**Comment by favourmark05** [comment]
Hi, @BolajiAyodeji 
changes has been made.
Thanks

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji,
I haven't gotten feedback about the event.
Still expecting response .

Thanks

Mfonido Mark
Osca Ikot-Ekpene

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, thanks for the update and apologies for the delayed response.

Your event looks good to me; great work! Please go ahead and start making the necessary arrangements.

Looking forward to your post-event report, cheers!

**Comment by favourmark05** [comment]
@BolajiAyodeji 
Thanks for your assistance in organizing this event.

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, please don't close your issue yourself. Instead, ensure to submit your post-event report following the correct format, and we will review it, provide feedback and close the issue ourselves.

Looking forward to your post-event report; cheers!

**Comment by favourmark05** [comment]
Hi @BolajiAyodeji Thanks for the headsup.. I did submit the post event form, hope you have seen it..

Thanks..

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, you should submit your post-event report as a comment in your initial issue and not as a pull request. Please revert and check some closed issues for samples. Looking forward to your post-event report; cheers!

**Comment by favourmark05** [comment]
# Post Event Report [GENESIS OF OPEN SOURCE IN IKOT-EKPENE] [19-JULY 2021]

> Kindly use this template to fill out a report about your just-concluded event. You don't need to include all the headings used below, as this is just a template to get you started. Feel free to delete headings that are not relevant to your event or add new ones as you deem fit.

## Attendance 🔵

_What was the attendance like? Was there a diverse attendance in terms of gender, race, socio-economic class, work status?_
Although it was supposed to be an online event it turn out to be a physical event due to some situations beyond the team control, we had 65 persons in attendance.

## Event Venue 🟣

_Any comments on the event venue? What worked well for you? Did you experience any difficulties?_
The venue used for the event was a hall that was gotten with the help of me and the core team members, and the hall was conducive enough for all the participants of the event, while we observed strict covid-19 protocols. the hall was well equipped with Audiovisual aid for learning.

## The Good, Bad, and Ugly 🔴

_Did all your plans before the event (schedule, budget, logistics, e.t.c) work well during the event? What didn't work well?_

_Feel free to share your positive and negative experiences here with bullet points._

The majority of the plans went well except the fact that it was supposed to be an online event, but later turned out to be a physical event, which actually made the turn out to be very much exciting


## TIL (Today I Learned) ⚪️

_What did you learn from organizing this event?_
Although this is not my first time organizing an event, I believe every time you do something, you tend to learn something new always, so this time, I learnt that we need to be flexible enough in our planning of anything so that there can be room for adjustment if need be.


## Feedback from Attendees 🟠

_Did attendees share any feedback? (Please ensure you have permission to use any attendee's comment(s))._
Most of the attendees appreciated the idea behind the event and said it was a welcome development in Ikot-Ekpene, and are looking forward to more events being hosted and more importantly more ways of gaining and sharing knowledge.

*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)* 
*How and when did you get the feedback? (During the event, social media, after the event, feedback survey forms, e.t.c)*
This feedback was gotten during and after the event.

## Social Media Highlights ⚫️

_Include links to any social posts about the event from any social media platform_
The only social media platform we have is Twitter and for now, it is currently banned in Nigeria

## Event Photos 🟢

_Embed images from the event here or add a link to an image repository, drive, or public folder where we can access your event images_
https://drive.google.com/drive/folders/1zzqMLypGHBQt-H7uRF-eJhf-BoSRcRsL?usp=sharing


## Summary 🟡

_Generally, what's your overview of the event?_
The event was impactful, thank God we made it physical at the last minute, most of the participants said they wouldn’t have attended it if it was to be an online event.

_How did it go for you as a Chapter Lead?_
It was a nice experience tho, it deposited positively to my bank of experiences when it comes to organizing events for communities and also working with a team.

_Looking forward to the next event? What changes will you be making based on your experience from this event?_
For the now, I don’t think I will be making any changes, Because all the plans for this event went perfectly okay, except for the fact that it was supposed to be an online event but, later became a physical one.

@BolajiAyodeji 
Thanks for the corrections

**Comment by BolajiAyodeji** [comment]
Hi @favourmark05, thanks for the detailed event report. We're happy to see that your first event went well.

Do you mind sharing the situations beyond your team's control that made you organize a physical event, please?

Great work once again!
