### ISSUE TITLE
OSCAfrica ABUJA INAUGURAL OPEN SOURCE DAY | ABUJA CHAPTER - 2021/05/29

### ISSUE THREAD

**Issue by adugamayuba** [oscafrica/chapter-leads-hub#15]
> Before you start, please follow the issue title format and assign yourself to this issue.

> If the event is a multiple date event, only add the starting date in the title.

> Please note that we need **2 weeks minimum and 3 weeks maximum notice** to approve proposed events.

> Please note that we need **21 days maximum notice** to provide support from your request.

## Event information
_Please complete all applicable._

- **Event name**: OSCAFRICA Abuja Inaugural Open source day 
- **Event date**: _21/05/29_
- **Estimated number of attendees**: 50
- **Event location**: Abuja, Federal Capital Territory
- **Event description**: This event is to set the motion and momentum for the open source eco system in Abuja, we will be talking about Open source and everything it entitles, what it means, how to be part and all those viral information for both newbies and expert in this industry.

## How does this benefit your chapter?
_Please let us know why we should approve this event._

Establishing a stand and a presence for the open source communities in Abuja is crucial to building a successful open source community.

And for that reason this inauguration OSCAfrica Abuja event, will be setting a path for a successful open source community ecosystem.

## What help do you need with this event? 
_Tell us how Open Source Community Africa can help with this event._
Sponsorship support.

## Checklist

**Before you post the issue**: 
- [*] You have followed the issue title format.
- [*] You have applied the correct labels (Country, Type of Event, Requests).
- [*] You have completed the [request form](https://bit.ly/osca-cl-request) for sponsorship.

**Before the event**: 
- [ ] Your event is approved.
- [ ] Your event's RSVP page has been created on [Open Collective](https://opencollective/osca).
- [*] You have received your sponsorship (if requested).

**After the event**:  
- [ ] You have completed the [post-event report](/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all related expense receipts for this event.
- [ ] This issue is closed.

**Comment by adugamayuba** [comment]
Hi @BolajiAyodeji I can't seems to add the labels, a little help please

**Comment by BolajiAyodeji** [comment]
Hi @adugamayuba, thanks for submitting this ticket!

We'll get back to you concerning your event request. We also need to figure out how to grant all leads access to add tags to issues. You can skip this for now until we get back to you with instructions. Cheers!

**Comment by adugamayuba** [comment]
Oh okay, that explains why I was having trouble adding the tag.

Thanks Bolaji.

**Comment by BolajiAyodeji** [comment]
Hi @adugamayuba, sincere apologies for the delayed response. This is due to the multiple internal meetings we had concerning physical events and how we want to support you and your community. Here are the feedbacks we have for you:

While we understand that physical events amass more attendees than virtual events, which is appropriate for an inaugural event. We would advise you NOT to host a physical event yet due to the ongoing COVID-19 pandemic. It is ideal for you to host a virtual event and keep yourself and your community safe. Also, the Federal Government of Nigeria recently announced a restriction on public gatherings from 11th May till 11th June 2021, which further confirms the need to go remote for now till the virus is contained.

Despite all said, our plans to kick-start the chapter's program was built around virtual and remote activities due to all that's happening globally, so we are not fully ready financially and resource-wise to shoulder the costs of hosting a physical event. However, we are actively working to prepare ourselves for the post-remote life when you are fully allowed to gather your community physically. Be rest assured that we will support you to host physical events when the time is right.

So, we advise you to make a new plan/budget to host a virtual event and let us know how we can support you in making your inaugural virtual event a success. Support here can include requesting an internet subscription for yourself or your community members as required. We also encourage you to build your community and outreach to neighboring communities to expose them to the amazing stuff you have planned. This will help make your first event even more successful.

Lastly, there are a couple of things that need to be improved in your budget, especially around allocation and descriptive communication. Hence, we will discuss more about this generally in the next leads community call so you and other leads can learn about what we expect from you in terms of budgeting. Apologies once again for any inconvenience this will cause you. We're super proud of you and your community and can't wait to see you shine.

Do let us know if you need anything, and we'll be here to help. Cheers!

**Comment by BolajiAyodeji** [comment]
Hi @adugamayuba 👋🏾

We haven't heard from you for a while now.

**Comment by BolajiAyodeji** [comment]
Hi @adugamayuba 👋🏾

We haven't heard from you for a while now. Please let us know what you think and how we can help, thanks.
