### ISSUE TITLE
Introduction to Web Development and Version Control(Git and Github) | MAIDUGURI - 2021/07/12

### ISSUE THREAD

**Issue by mikailyusuf** [oscafrica/chapter-leads-hub#33]
## Event information

- **Event name**: Introduction to web development and Version Control
- **Event description**:In this event we would introduce members to Web development and  the basic tools used in contributing to open source
- **Event  start date**: 2021/07/12
- **Event  end date**: 2021/08/08
- **Event time**: Thurday's ,Fridays by 3:30pm-6:30pm and Saturday's by 9-12 am (GMT +1)
- **Event duration**:3 Weeks
- **Event location**:Virtual (Google Meet)
- **Estimated number of attendees**: 25-40

## How does this benefit your chapter?
This event would help chapter members build their first website and know what are the basic tools used to contribute to open souce

## What help do you need with this event? 
Approve this event, some funding and swags(T-shirts and stickers) to make it a success.

## Checklist

**Before you post the issue**: 
- [x] You have followed the issue title format.
- [x] You have applied the correct labels (Country, Type of Event, Requests).
- [x] You have completed the [request form](https://bit.ly/osca-cl-request) (if you need sponsorship).

**Before the event**: 
- [x] Your event is approved.
- [x] Your event's RSVP page has been created.
- [x] You have received your sponsorship (if requested).

**After the event**:  
- [x] You have completed the [post-event report](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/post-event-template.md).
- [ ] You have submitted all [related expense receipts](https://github.com/oscafrica/chapter-leads-hub/blob/master/docs/expenses.md#tracking-your-expenses) for this event.
- [ ] This issue is closed.

**Comment by BolajiAyodeji** [comment]
Hi @mikailyusuf,

Unfortunately, we cannot provide financial support for your event as you failed to meet the 21 days maximum notice. You also failed to meet the required 2 weeks minimum and 3 weeks maximum notice for proposed events. Please ensure to read your [onboarding guide](https://docs.oscafrica.org/community/chapters/chapter-leads-onboarding-guide) and the instructions on the issue template before submitting your issue.

Because this is your first event and virtual, we will give you the go-ahead to host your event if you can without the financial support requested, or you can choose to cancel and re-schedule your event. Please ensure to take note of the feedback and make changes for your next event.

While we understand that physical events amass more attendees than virtual events, we would advise you NOT to host a physical event yet due to the ongoing COVID-19 pandemic. It is ideal for you to host a virtual event and keep yourself and your community safe. Also, you didn't clearly specify the exact dates of the virtual event during the 3 weeks you highlighted.

Great work! Kindly let us know your decision; cheers!

**Comment by mikailyusuf** [comment]
@BolajiAyodeji I have made the changes requested, pls review

**Comment by BolajiAyodeji** [comment]
Hey @mikailyusuf. Thanks for making the changes.

This looks good to me. Can you update your budget to reflect the feedback mentioned earlier about not having physical events? Kindly let me know once you do, and please go ahead and start making the necessary arrangements.

We're super proud of you and your community and can't wait to see you shine.

**Comment by mikailyusuf** [comment]
Top of the day to you Boss @BolajiAyodeji , I have updated the Google Sheet as requested , But the amount inputed is different from the Google form  that i filled for Sponsorship, pls let me know if i should fill a new form

**Comment by BolajiAyodeji** [comment]
Hi @mikailyusuf, thanks for the update. We'll review it and get back to you next week. You don't have to fill a new form, thanks!

**Comment by BolajiAyodeji** [comment]
Hey, @mikailyusuf, thanks for making the changes!

This looks good to me. Don't forget to create a registration form using [Google Forms](https://docs.google.com/forms) or your preferred platform to track the number of people registering for the event.

We're super proud of you and your community and can't wait to see you shine.

**Comment by mikailyusuf** [comment]
Top of the day @BolajiAyodeji , I requested sponsorship for this event , and the due date was yesterday, 
My community would begin the mentorship on thursday.

**Comment by BolajiAyodeji** [comment]
> Top of the day @BolajiAyodeji , I requested sponsorship for this event, and the due date was yesterday,
> My community would begin the mentorship on thursday.

Hi @mikailyusuf, sincere apologies for the delayed response to your funding. We experienced some delays with our systems, but we have disturbed your request today.

Please don't forget to submit your expenses and receipts after your event is completed. Again, great work, and I look forward to your post-event report.

**Comment by BolajiAyodeji** [comment]
Hi @mikailyusuf, thanks for sending in your report. We're glad it went well and you learned something new yourself. Please don't forget to complete your expense report as required. Great work!
